name: Requirement
type: Requirement
description: Submit a new requirement.
title: "Short objective of the requirement"
projects: ["tce-dip/2"]
body:
    
  - type: input
    id: actor
    attributes:
      label: Actor
      description: The <a href="https://fuzzy-goggles-j8o2698.pages.github.io/documentation/process/development-proccess.html#actor" target="blank">external person, system, or trigger</a> that provides input or receives the output of this requirement.
      placeholder: examples: KAM Manager | Financial Controller | System Notification | ServiceBus Message
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        > [!TIP]
        > An actor specifies a role played by a _user_ or any other _system_ that interacts with the objective of this requirement.
        > Actors are _external_ to the requirement, but interact with it directly by _providing input_ to it, and/or _receive outputs_ from it.
        > An actor is not necessarily a physical entity, for example, it may be a _trigger_ or another type of _event_.

  - type: textarea
    id: objective
    attributes:
      label: Objective
      description: The [overall objective](https://fuzzy-goggles-j8o2698.pages.github.io/documentation/process/development-proccess.html#objective) of this requirement in a single sentence?
      placeholder: "example: The first tab in the report must display a chart that depicts spending by category."
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        > [!TIP]
        > The objective is a _single_, _complete_ and _unambiguous_ sentence that describes the desired _end-state_ of this requirement.
        > It includes a subject and a predicate with an object. Keep the following in mind when composing the objective:
        >     - Is it a complete and unambiguous sentence?
        >     - Is it not in conflict with any other requirements?
        >     - Is it an atomic (single unit) of work?
        >     - Is it feasible within a single iteration?
        >     - It it valuable?
        
  - type: textarea
    id: context
    attributes:
      label: Context
      description: Describe the [<b>context</b>, add <b>background information</b>, and list any <b>preconditions</b>](https://fuzzy-goggles-j8o2698.pages.github.io/documentation/process/development-proccess.html#context) that are important for the implementation of this requirement.

  - type: markdown
    attributes:
      value: "# Requirements Guidance"
  - type: markdown
    attributes:
      value: "The functional en non-functional requirements form the core of this requirement"
    
  - type: textarea
    id: requirements-functional
    attributes:
      label: Functional Requirements
      description: List the [functional requirements](https://fuzzy-goggles-j8o2698.pages.github.io/documentation/process/development-proccess.html#functional-requirements) and their [<b>MoSCoW</b>](https://fuzzy-goggles-j8o2698.pages.github.io/documentation/process/development-proccess.html#moscow) classification.
      placeholder: |
        - [ ] List any functional prerequisites, for example using a link: tce-dip/tce-dip-connectors-template#30.
        - [ ] List the functional requirements that <i>must / should / could / would</i> be implemented.
        - [ ] List the functional requirements that <i>must / should / could / would</i> be implemented.
    validations:
      required: true

  - type: textarea
    id: requirements-non-functional
    attributes:
      label: Non-Functional Requirements
      description: List the [non-functional requirements](https://fuzzy-goggles-j8o2698.pages.github.io/documentation/process/development-proccess.html#non-functional-requirements) and their [<b>MoSCoW</b>](https://fuzzy-goggles-j8o2698.pages.github.io/documentation/process/development-proccess.html#moscow) classification.
      value: |
        - [ ] List any non-functional prerequisites, for example using a link: tce-dip/tce-dip-connectors-template#30.
        - [ ] Readme and other documentation updated.
        - [ ] Deployment scheduled or carried out.
    validations:
      required: true
