name: Task
type: task
description: "A specific task that should be executed which is not a requirement."
title: "Objective of the Task (do NOT add prefixes such as 'System | CODE' | ...)"
projects: ["tce-dip/2","tce-dip-products/2"]
body:

  - type: markdown
    attributes:
      value: |
        > [!TIP]
        > The objective is a _single_, _complete_ and _unambiguous_ sentence that describes the desired _end-state_ of this task.
        > It includes a subject and a predicate with an object.
        >
        > Examples:
        >    - Compare option 1 to option 2 in order to decide their suitability.
        >    - Estimate the effort for Phase 1 of the Xyz Dashboard requirements
        >
        > Keep the following in mind when composing the objective:
        >    - Is it a complete and unambiguous sentence?
        >    - Is it not in conflict with any other tasks?
        >    - Is it an atomic (single unit) of work?
        >    - Is it feasible within a single iteration?
        >    - It it valuable or considered busywork?

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide an optional **context** relevant to the completion of this task.

  - type: markdown
    attributes:
      value: |
        > [!TIP]
        > The context of the task provides background information:
        >     - Why is the task important or which particular question or need has resulted in this task.

  - type: textarea
    id: desired-outcome
    attributes:
      label: Desired Outcome
      description: List the _desired outcomes_ and their **MoSCoW** classification.
      placeholder: |
        - [ ] List any prerequisites, for example using a link to another task.
        - [ ] List the desired <i>must, should, could, or would</i> outcomes.
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        > [!TIP]
        > The desired outcomes comprise all expectations of this task:
        >     - List the _exact_ and _detailed_ expectations of this task.
        >     - Most desired outcomes should be _verifyable_, but may not be.
        >     - Use the MoSCow classification to indicate priority, provide focus, or allow some interpretation.

  - type: textarea
    id: completion-steps
    attributes:
      label: Completion Steps
      description: List the steps required, in their preferred order, to complete this task.
      placeholder: |
        - [ ] Step 1 (optional @assignee)
        - [ ] Step 2 (optional @assignee)
        - [ ] Step 3 (optional @assignee)
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        > [!TIP]
        > The completion steps define the path to executing the task and should be output of the refinement session(s).
        > The steps should directly reflect the desired outcomes. No more, no less.
        > The steps may optionally be assigned an assignee.
