name: Documentation
type: documentation
description: "A task to create or update documentation."
title: "Objective of the documentation task"
projects: ["tce-dip/2","tce-dip-products/2"]
body:

  - type: markdown
    attributes:
      value: |
        > [!TIP]
        > The objective is a _single_, _complete_ and _unambiguous_ sentence that describes the desired _end-state_ of this task.
        > It includes a subject and a predicate with an object.
        >
        > Examples:
        >    - Compare option 1 to option 2 in order to decide their suitability.
        >    - Estimate the effort for Phase 1 of the Xyz Dashboard requirements
        >
        > Keep the following in mind when composing the objective:
        >    - Is it a complete and unambiguous sentence?
        >    - Is it not in conflict with any other tasks?
        >    - Is it an atomic (single unit) of work?
        >    - Is it feasible within a single iteration?
        >    - It it valuable or considered busywork?

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide an optional **context** relevant to the completion of this task.

  - type: dropdown
    id: site
    attributes:
      label: Target Site
      description: Where should this documentation be created or updated?
      multiple: false
      options:
        - Code
        - Model
        - Portal
        - Repo
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        > [!TIP]
        > The context of the documentation task provides background information:
        >     - Why is the documentation important or which particular question or need has resulted in this documentation task.

  - type: textarea
    id: requirements-documentation
    attributes:
      label: Documentation Requirements
      description: List the _documentation_ requirements and their **MoSCoW** classification.
      placeholder: |
        - [ ] List any prerequisites, for example using a link to an issue or task.
        - [ ] List the documentation requirements that <i>must, should, could, or would</i> be implemented.
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        > [!TIP]
        > The documentation requirements (which fall under the category NFR's) comprise all necessary additions and updates to the documentation for it to be useful for its target audience.

